language: sml
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --force-yes docker ; fi
install:
  - docker run -v "$PWD":"$PWD" -w "$PWD" shwestrick/mpl make
script:
  - make test
  
notifications:
  email: false
