language: sml
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --force-yes mlton ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlton ; fi
install:
  - make
script:
  - ./heron --use examples/basic/FirstExample.tesl
  - ./heron --use examples/basic/Implications.tesl
  - ./heron --use examples/basic/ImplicationsTimeScales.tesl
  - ./heron --use examples/basic/FilteredImplication.tesl
  - ./heron --use examples/basic/DelayedImplication.tesl
  - ./heron --use examples/basic/SustainedImplication.tesl
  - ./heron --use examples/basic/WhenImplication.tesl
  - ./heron --use examples/basic/AwaitImplication.tesl
  - ./heron --use examples/basic/TimeDelayed.tesl
  - ./heron --use examples/gallery/ConcurrentComputations.tesl
  - ./heron --use examples/gallery/LightSwitch.tesl
  - ./heron --use examples/gallery/LeapYears.tesl
  - ./heron --use examples/gallery/Engine.tesl
  
notifications:
  email: false
